---
name: ndiag architecture
docPath: docs/arch
descPath: docs/ndiag.descriptions
hideLayers: true
hideLabels: true
graph:
  attrs:
    rankdir: LR
dict:
  'Nodes': 'Components'
views:
  -
    name: "overview"
    layers: ["type"]
  -
    name: "input"
    layers: ["type"]
    labels: ["input"]
  -
    name: "output"
    layers: ["type"]
    labels: ["output"]
nodes:
  -
    name: input files
    components:
      - ndiag.yml?icon=text
      - nodes.yml?icon=text
      - ndiag.descriptions/*.md?icon=doc
    clusters:
      - 'type:input'
  -
    name: ndiag
    components:
      - internal?icon=hex2
  -
    name: documents
    components:
      - 'index document?icon=text'
      - 'custom documents?icon=doc'
      - 'layer based documents?icon=doc'
      - 'label based documents?icon=doc'
    clusters:
      - 'type:output'

networks:
  -
    labels:
      - input
    route:
      - 'input files:ndiag.yml'
      - 'ndiag:internal'
  -
    labels:
      - input
    route:
      - 'input files:nodes.yml'
      - 'ndiag:internal'
  -
    labels:
      - input
    route:
      - 'input files:ndiag.descriptions/*.md'
      - 'ndiag:internal'
  -
    labels:
      - output
    route:
      - 'ndiag:internal'
      - 'input files:ndiag.descriptions/*.md'
  -
    labels:
      - output
    route:
      - 'ndiag:internal'
      - 'documents:index document'
  -
    labels:
      - output
    route:
      - 'ndiag:internal'
      - 'documents:custom documents'
  -
    labels:
      - output
    route:
      - 'ndiag:internal'
      - 'documents:layer based documents'
  -
    labels:
      - output
    route:
      - 'ndiag:internal'
      - 'documents:label based documents'
