---
name: 3-Tier Architecture
docPath: ../output
views:
  -
    name: overview
    layers: ["consul", "vip_group"]
  -
    name: http-lb
    layers: ["vip_group"]
    labels: ["http"]
nodes:
  -
    name: lb-*
    components:
      - nginx?icon=lb-l7
    clusters:
      - 'consul:dc1'
      - 'vip_group:lb'
  -
    name: app-*
    components:
      - nginx?icon=proxy
      - Rails?icon=cube4&label=ruby
    clusters:
      - 'consul:dc1'
  -
    name: db-*
    components:
      - PostgreSQL?icon=db
    clusters:
      - 'consul:dc1'

networks:
  -
    labels:
      - http
    route:
      - "internet?icon=cloud"
      - "vip_group:lb:vip"
  -
    labels:
      - http
    route:
      - "vip_group:lb:vip"
      - "lb-*:nginx"
  -
    labels:
      - http
      - app
    route:
      - "lb-*:nginx"
      - "app-*:nginx"
      - "app-*:rails"
  -
    labels:
      - app
    route:
      - "app-*:rails"
      - "db-*:postgresql"

relations:
  -
    labels:
      - http
    components:
      - 'lb-*:keepalived?icon=keepalived'
      - "vip_group:lb:vip"

customIcons:
  -
    key: keepalived
    lines:
      - b1 b5 f9 j5 j1 f1 b1
      - d2 d6
      - h2 d4
      - e4 h6
